Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.IO.Compression.FileSystem
$ErrorActionPreference = "Stop"
function PickFolder([string]$d){$x=New-Object System.Windows.Forms.FolderBrowserDialog;$x.Description=$d;if($x.ShowDialog() -ne 'OK'){throw '操作已取消。'};$x.SelectedPath}
function PickFile([string]$d){$x=New-Object System.Windows.Forms.OpenFileDialog;$x.Title=$d;$x.Filter='Excel 工作簿 (*.xlsx)|*.xlsx';$x.InitialDirectory=$PSScriptRoot;if($x.ShowDialog() -ne 'OK'){throw '操作已取消。'};$x.FileName}
function PickOutput([string]$d){$x=New-Object System.Windows.Forms.SaveFileDialog;$x.Title='选择输出工作簿';$x.Filter='Excel 工作簿 (*.xlsx)|*.xlsx';$x.InitialDirectory=$d;$x.FileName='Tmall_Imported.xlsx';if($x.ShowDialog() -ne 'OK'){throw '操作已取消。'};$x.FileName}
function Stem($f){$f.BaseName.Trim().Normalize([Text.NormalizationForm]::FormKC).ToLowerInvariant()}
function Cell($doc,[string]$ref,[string]$val){$c=$doc.SelectSingleNode("//*[local-name()='c' and @r='$ref']");if($null -eq $c){$rn=[regex]::Match($ref,'\d+').Value;$r=$doc.SelectSingleNode("//*[local-name()='row' and @r='$rn']");$c=$doc.CreateElement('c',$doc.DocumentElement.NamespaceURI);$c.SetAttribute('r',$ref);$col=[regex]::Match($ref,'^[A-Z]+').Value;$before=$null;foreach($e in $r.SelectNodes("*[local-name()='c']")){if([String]::CompareOrdinal([regex]::Match($e.GetAttribute('r'),'^[A-Z]+').Value,$col)-gt 0){$before=$e;break}};if($null -eq $before){$r.AppendChild($c)|Out-Null}else{$r.InsertBefore($c,$before)|Out-Null}};while($c.HasChildNodes){$c.RemoveChild($c.FirstChild)|Out-Null};if([String]::IsNullOrEmpty($val)){return};$c.SetAttribute('t','inlineStr');$is=$doc.CreateElement('is',$doc.DocumentElement.NamespaceURI);$t=$doc.CreateElement('t',$doc.DocumentElement.NamespaceURI);$t.InnerText=$val;$is.AppendChild($t)|Out-Null;$c.AppendChild($is)|Out-Null}
$tmp=Join-Path ([IO.Path]::GetTempPath()) ('tmall_'+[guid]::NewGuid().ToString('N'))
try{$template=PickFile '第 1 步：选择视频或图文模板';$isImage=$false;$imageHeader=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('5Zu+54mH5paH5Lu25aS56Lev5b6E'));$zip=[IO.Compression.ZipFile]::OpenRead($template);try{$entry=$zip.GetEntry('xl/worksheets/sheet1.xml');$sr=New-Object IO.StreamReader($entry.Open());$head=$sr.ReadToEnd();$isImage=$head.Contains($imageHeader)}finally{$zip.Dispose()}
  $source=PickFolder $(if($isImage){'第 2 步：选择包含图文任务文件夹的总文件夹'}else{'第 2 步：选择视频文件夹'});$cover=$null;if(-not $isImage){$useCover=[Windows.Forms.MessageBox]::Show('是否导入封面文件？','可选封面','YesNo','Question');if($useCover -eq 'Yes'){$cover=PickFolder '第 3 步：选择封面文件夹'}};$out=PickOutput (Split-Path $template);if([String]::Equals($template,$out,[StringComparison]::OrdinalIgnoreCase)){throw '输出文件不能覆盖模板。'}
  $videoExt=@('.mp4','.mov','.avi','.mkv','.wmv','.flv','.m4v','.webm');if($isImage){$files=@(Get-ChildItem -LiteralPath $source -Directory|sort Name)}else{$files=@(Get-ChildItem -LiteralPath $source -File -Recurse|?{$videoExt -contains $_.Extension.ToLowerInvariant()}|sort FullName)};if($files.Count -eq 0){throw '没有找到支持的文件。'};if($files.Count -gt 200){throw '模板最多支持 200 行。'}
  $map=@{};if($null -ne $cover){foreach($f in @(Get-ChildItem -LiteralPath $cover -File -Recurse)){if(!$map.ContainsKey((Stem $f))){$map[(Stem $f)]=$f.FullName}}};New-Item -ItemType Directory $tmp|Out-Null;[IO.Compression.ZipFile]::ExtractToDirectory($template,$tmp);$sp=Join-Path $tmp 'xl\worksheets\sheet1.xml';$doc=New-Object Xml.XmlDocument;$doc.PreserveWhitespace=$true;$doc.Load($sp);$cols=if($isImage){@('A','B','C','D','E','F','G','H','I','J')}else{@('A','B','C','D','E','F','G','H','I','J','K')};for($r=2;$r -le 201;$r++){foreach($c in $cols){Cell $doc "$c$r" ''}};$miss=0;for($i=0;$i-lt$files.Count;$i++){$r=$i+2;Cell $doc "A$r" $files[$i].FullName;if($null -ne $cover){$k=Stem $files[$i];if($map.ContainsKey($k)){Cell $doc "B$r" $map[$k]}else{$miss++}}};$doc.Save($sp);if(Test-Path $out){Remove-Item $out -Force};[IO.Compression.ZipFile]::CreateFromDirectory($tmp,$out);$kind=if($isImage){'图文文件夹'}else{'视频'};$msg="完成（$kind 模板）。`r`n文件数量：$($files.Count)";if($null -ne $cover){$msg+="`r`n已匹配封面：$($files.Count-$miss)`r`n未匹配视频：$miss"}elseif(-not $isImage){$msg+="`r`n封面：已跳过"};$msg+="`r`n`r`n输出文件：$out";[Windows.Forms.MessageBox]::Show($msg,'天猫路径导入','OK','Information')|Out-Null}catch{[Windows.Forms.MessageBox]::Show($_.Exception.Message,'导入失败','OK','Error')|Out-Null;exit 1}finally{if(Test-Path $tmp){Remove-Item $tmp -Recurse -Force}}
